### ISSUE TITLE
Dependency not resolved

### ISSUE THREAD

**Issue by PremaV** [oliveagle/jsonpath#1]
Hi,

I had done a go get of jsonpath. When i tried compiling it say fails with missing dependency. I couldn't get the dependency from net. It was "golang../types" the files are missing inside this and your library uses it.

**Comment by oliveagle** [comment]
from 1.5, google moved this package into golang src.

[https://golang.org/pkg/go/types/](https://golang.org/pkg/go/types/)

**Comment by oliveagle** [comment]
46b039cf586ce41b6ef05286230e38b648bbffe2 fixed

**Comment by PremaV** [comment]
thanks a lot oliveagle. Do you have any plans to add support for the rules that is not currently supported (*, ..).

**Comment by oliveagle** [comment]
I'll look into it.
