### ISSUE TITLE
Incentive

### ISSUE THREAD

**Issue by suntong** [oliveagle/jsonpath#2]
Hi, 

what's your incentive in developing this library (with so many out there already)?

Also, 

> this library is till bleeding edge

so how is the status now? Is it usable now? Are there still any unfinished items/ideas? 

Thanks

**Comment by oliveagle** [comment]
> so many out there already ?

I don't think so.  you can google `golang jsonpath` and take a look. Do they all follow `jsonpath search syntax` ?    

http://goessner.net/articles/JsonPath/  

> status now

All examples in readme are tested. U can run test yourself.  Compare to original JsonPath, not all syntax supported.  

unfinished syntax.

| Operator | Supported | Description |
| ---- | :---: | ---------- |
| * 					  | X | Wildcard. Available anywhere a name or numeric are required. |
| .. 					  | X | Deep scan. Available anywhere a name is required. 
| ['<name>' (, '<name>')] | X | Bracket-notated child or children |

**Comment by suntong** [comment]
Thank you Sir for the explanation.
