### ISSUE TITLE
filter condition with string == operation is not working

### ISSUE THREAD

**Issue by ranjithkommula** [oliveagle/jsonpath#6]
JSON : {
    "store": {
        "book": [
            {
                "category": "reference",
                "author": "Nigel Rees",
                "title": "Sayings of the Century",
                "price": 8.95
            },
            {
                "category": "fiction",
                "author": "Evelyn Waugh",
                "title": "Sword of Honour",
                "price": 12.99
            },
            {
                "category": "fiction",
                "author": "Herman Melville",
                "title": "Moby Dick",
                "isbn": "0-553-21311-3",
                "price": 8.99
            },
            {
                "category": "fiction",
                "author": "J. R. R. Tolkien",
                "title": "The Lord of the Rings",
                "isbn": "0-395-19395-8",
                "price": 22.99
            }
        ],
        "bicycle": {
            "color": "red",
            "price": 19.95
        }
    },
    "expensive": 10
}
JSON Path as $.store.book[?(@.author == 'Nigel Rees')].price

Result from this package is an empty []

**Comment by oliveagle** [comment]
fixed. 

added a new test case `Test_jsonpath_string_equal` 

`$.store.book[?(@.author == 'Nigel Rees')].price` expected to be `[8.95]`
