### ISSUE TITLE
String comparison is done instead of numeric comparison.

### ISSUE THREAD

**Issue by milindacharya** [oliveagle/jsonpath#7]
String comparison is done instead of numeric comparison.
```
{
	"books": [ 
                { "name": "My First Book", "price": 10 }, 
		{ "name": "My Second Book", "price": 20 } 
		]
}
```

```
$.books[?(@.price > 100)].name should return [], instead it returns ["My Second Book"]
```
The problem occurs in 
https://github.com/oliveagle/jsonpath/blob/f95233d869819eb2cf1df702347887ae1775817d/jsonpath.go#L546
where obj1 and obj2 are interpreted as string and compared.

**Comment by oliveagle** [comment]
thx  :)  the initial implementation is a little bit naive.

**Comment by milindacharya** [comment]
Thanks for a quick turnaround.
