### ISSUE TITLE
Is the deepcopy needed?

### ISSUE THREAD

**Issue by superfell** [oliveagle/jsonpath#8]
I was looking at some CPU profiles from code that calls JsonPathLookup and it spends the vast majority of its time on the xobj := deepcopy.Iface(obj) call. I was wondering why the copy is needed, is xobj mutated somewhere during the evaluation? I did a quick scan of the code and didn't spot anywhere that did.

**Comment by superfell** [comment]
FWIW, i took the deepcopy out and didn't see any test failures.

**Comment by superfell** [comment]
If we can get rid of the copy, then there's a significant perf jump available

pkg: github.com/oliveagle/jsonpath
Benchmark_JsonPathLookup-8   	  100000	     13516 ns/op
PASS

to
pkg: github.com/oliveagle/jsonpath
Benchmark_JsonPathLookup-8   	 1000000	      1635 ns/op
PASS

**Comment by oliveagle** [comment]
you are right. no mutation happened . I removed `deepcopy`. thank you to point it out.
